theme: ''
disableNewStartMenuLayout: 0

controlStyles:
  # User Profile Text
  - target: // TextBlock#UserName
    styles:
      - Text=Username Here
      - FontSize=16
      - ToolTipService.ToolTip:=
  - target: // TextBlock#UserAccount
    styles:
      - Text=Microsoft Account
      - ToolTipService.ToolTip:=

  # Search Box
  - target: StackPanel#SettingsCommandSearchBoxBackground
    styles:
      - CornerRadius=4
  - target: TextBox#CommandSearchTextBox
    styles:
      - CornerRadius=4
  - target: TextBox#CommandSearchTextBox > Grid > Button#DeleteButton > Grid#ButtonLayoutGrid
    styles:
      - CornerRadius=3

  # Page Title
  - target: ContentControl#HeaderContent > ContentPresenter
    styles:
      - Margin=0,20,0,0

  # Hide the MS 365 & OneDrive buttons
  - target: SystemSettings.View.AlignableContentControl#heroContent > ContentPresenter > SystemSettings.View.AlignableContentControl > ItemsControl > ItemsPresenter > StackPanel > ContentPresenter > SystemSettings.View.AlignableContentControl > ContentPresenter > SystemSettings.View.HeroUserControl#HeroUserControl > Grid#LayoutRoot > ItemsControl#CharmGrid > ItemsPresenter > SystemSettings.View.EntityWrapPanel#CharmEntityWrapPanel > ContentPresenter[1]
    styles:
      - Visibility=Collapsed
  - target: SystemSettings.View.AlignableContentControl#heroContent > ContentPresenter > SystemSettings.View.AlignableContentControl > ItemsControl > ItemsPresenter > StackPanel > ContentPresenter > SystemSettings.View.AlignableContentControl > ContentPresenter > SystemSettings.View.HeroUserControl#HeroUserControl > Grid#LayoutRoot > ItemsControl#CharmGrid > ItemsPresenter > SystemSettings.View.EntityWrapPanel#CharmEntityWrapPanel > ContentPresenter[2]
    styles:
      - Visibility=Collapsed

  # Network Data Usage indicator bars
  # Make it less eyesore with Dark theme
  - target: ProgressBar#appBar > Grid > Border#DeterminateRoot
    styles:
      - Background=#60808080

  # Bluetooth & devices - Device names
  # Wrap the device names into two lines
  - target: SystemSettings.View.SettingsListView#DevicesHeroControlList > Border > ScrollViewer#ScrollViewer > Border#Root > Grid > ScrollContentPresenter#ScrollContentPresenter > ItemsPresenter > StackPanel > SystemSettings.View.SettingsListViewItem > Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenter#Root > ContentControl > ContentPresenter > UserControl > Button#DevicesHeroControlButton > ContentPresenter#ContentPresenter > StackPanel > ContentPresenter > StackPanel > ContentControl > ContentPresenter > TextBlock
    styles:
      - TextWrapping=2
      - MaxLines=2

  # Fix some issues when navigating to Personalization â†’ Background
  # - The in-line navigation pane BG becomes opaque, resulting in no Mica effect
  # - The page title is center aligned when leaving the Background section
  - target: Grid@DisplayModeStates > Grid#PaneRoot
    styles:
      - Background@OpenInlineLeft=Transparent
      - // Background@OpenOverlayLeft:=<SolidColorBrush FallbackColor="{StaticResource SystemChromeMediumColor}" />
      - // Background@Closed:=<SolidColorBrush FallbackColor="{StaticResource SystemChromeMediumColor}" />
  - target: SystemSettings.View.AlignableContentControl#PermanentNavViewHeaderAlignControl
    styles:
      - HorizontalAlignment=Left

webContentStyles:
  - target: ''
    styles:
      - ''
webContentCustomJs: ''
styleConstants:
  - ''
resourceVariables:
  - variableKey: ''
    value: ''
